# Duplicate of dockerfile for 7.1 from https://github.com/maxpou/docker-symfony
FROM henres/php-fpm-composer:7.1

MAINTAINER Henri d Auvigny <henri.dauvigny@gmail.com>

# enable mysql
RUN docker-php-ext-enable pdo pdo_mysql
